### ISSUE TITLE
Filename with three dots '...' is causing checkout failure. 

### ISSUE THREAD

**Issue by ZYFDroid** [liujing04/Retrieval-based-Voice-Conversion-WebUI#1]
![image](https://user-images.githubusercontent.com/39429452/229262702-8eba2cf5-2fff-4f45-b2f2-f0e37e8fb4c9.png)

**Comment by lclichen** [comment]
临时解决：在文件夹中执行 `git restore --source=HEAD :/`

**Comment by fumiama** [comment]
I have deleted it in #4

**Comment by liujing04** [comment]
Issue solved.

**Comment by AIhasArrived** [comment]
Hello @fumiama, @lclichen , @ZYFDroid , I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
