### ISSUE TITLE
Readme had the wrong command for torch installation on windows

### ISSUE THREAD

**Issue by rikimtasu** [liujing04/Retrieval-based-Voice-Conversion-WebUI#21]
Command was written on current readme:
`pip install torch torchvision torchaudio`
This is for Linux platform only
Correct command written on PyTorch website for CUDA 11.7:
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`

Doing this fixed my problem with RVC webui not detecing my RTX 3070

**Comment by liujing04** [comment]
已加入readme提示

**Comment by maxiedaniels** [comment]
@rikimtasu I tried this to fix my 3080 but now I get: "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.1 which is incompatible."

How did you fix this??

**Comment by TripleKiller666** [comment]
> @rikimtasu I tried this to fix my 3080 but now I get: "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.1 which is incompatible."
> 
> How did you fix this?? _edit_ I tried tweaking the numba requirement in the pyproject.toml, but can't get it working. Even torchaudio is failing because it says it requires torch 2.0.0.

either delete the venv folder (if you created one) on reinstall everything from new or try: 
"pip install -upgrade torch torchvision torchaudio --index-url https:/download.pytorch.org/whl/cu118"
 replace the cu118 with whatever cuda you need, like cu117 for example.

**Comment by Mejnun333** [comment]
I have a 3070 laptop. For windows do we write this directly into cmd?

**Comment by Mejnun333** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/350
This work for me (Windows)

**Comment by ChessScholar** [comment]
I'm not great at this, but I want to thank you for the post. I had to uninstall the current pytorches and stuff then reinstall with the correct ones for my 4070.

First:
`pip3 uninstall torch torchvision torchaudio`

Second:
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

That first step is important otherwise attempting the 2nd step will get a "requirement satisfied" or whatever when it finds the other cu### already installed.

I just started with cu121 because that was the first one I found online for my card. It can be updated...
