### ISSUE TITLE
执行一键包报错

### ISSUE THREAD

**Issue by fatinghenji** [liujing04/Retrieval-based-Voice-Conversion-WebUI#5]
Expecting value: line 1 column 1 (char 0)
提供webui截屏如下：
![image](https://user-images.githubusercontent.com/37131177/229326398-1e82d0cf-d8e4-4aa1-9210-8f01eb70eed6.png)
视频中指出说话人ID目前不需要进行改动：
![image](https://user-images.githubusercontent.com/37131177/229326632-c7621ec2-6746-4990-b5fe-37beb171e5e1.png)

**Comment by fatinghenji** [comment]
补充带有控制台的截图
![AR4_JIZS%2M(Y55B(4TRODJ](https://user-images.githubusercontent.com/37131177/229328578-a8a14c09-9800-4dda-b242-260604708188.png)

**Comment by liujing04** [comment]
查下系统代理问题，局域网区段不要代理

**Comment by AIhasArrived** [comment]
@fatinghenji  I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
